### ISSUE TITLE
Use a simpler execution library

### ISSUE THREAD

**Issue by beenotung** [Arcanemagus/check-peer-deps#15]
## Versions
| name | version |
|----|----|
| check-peer-deps | 1.1.0 |
| npm | 5.6.0 |
| yarn | 1.3.2 |
| node | v9.3.0 |

## console log
```
$ check-peer-deps 
[consistent-env] Unable to determine environment Error: Process execution timed out
    at Timeout._onTimeout (/home/beenotung/.config/yarn/global/node_modules/consistent-env/lib/helpers.js:60:14)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
[consistent-env] Unable to determine environment Error: Process execution timed out
    at Timeout._onTimeout (/home/beenotung/.config/yarn/global/node_modules/consistent-env/lib/helpers.js:60:14)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
[consistent-env] Unable to determine environment Error: Process execution timed out
    at Timeout._onTimeout (/home/beenotung/.config/yarn/global/node_modules/consistent-env/lib/helpers.js:60:14)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
[consistent-env] Unable to determine environment Error: Process execution timed out
    at Timeout._onTimeout (/home/beenotung/.config/yarn/global/node_modules/consistent-env/lib/helpers.js:60:14)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
[consistent-env] Unable to determine environment Error: Process execution timed out
    at Timeout._onTimeout (/home/beenotung/.config/yarn/global/node_modules/consistent-env/lib/helpers.js:60:14)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
[consistent-env] Unable to determine environment Error: Process execution timed out
    at Timeout._onTimeout (/home/beenotung/.config/yarn/global/node_modules/consistent-env/lib/helpers.js:60:14)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
```

**Comment by Arcanemagus** [comment]
Hmmm, so this should only be happening if you have some issue with your shell init script that is causing it to time out (>5 seconds). Generally this is caused by putting things that should only be used for _interactive_ shells in the general shell init script.

For now you should look into that, but I'll turn this into a request for a simpler way of executing `npm` since we don't need the environment fixing that `sb-exec` does. (It was written for use inside a GUI application that many OSs give a blank environment to.)
